### ISSUE TITLE
Pre-proposal: Type-aware allocators

### ISSUE THREAD

**Issue by Avi-D-coder** [rust-lang/wg-allocators#27]
Currently this use case is supported for the `Alloc` trait, but not `GlobalAlloc`.

As discussed in #18 generic methods (I.e`{alloc,dealloc}_one`) cannot be used to support this use case in `GlobalAlloc` and maybe removed from `Alloc`. An alternative that is consistent across both methods is needed.

Type information is necessary for ECS allocators, typed Pool/Slab allocators, many GC, STM optimizations, and describable for heap profilers, and exotic heuristic guided allocators as a significant source of free information.

- Today there are many slab and generational indexed allocators. They are incompatible with box, std, and each other. They all provide some version of the following: allocation and deallocation of `T: Sized`, indexing/dereferencing and usually iterating over `T`s.
  By passing  unsized allocations to an underlying or global allocator. They could easily implement the Alloc trait to take advantage of standard collections and boxes, but to do this they require knowing more than just `Layout`, they require `TypeId`.

- I am working on a  allocator for use a with both `Alloc` and `GlobalAlloc` that requires typed pools of `Sized` `T` to support pause free optional GC. Without a method of differentiating allocations and deallocations that share the same `Layout`, but different types my use case is impossible.

In order to support all the mentioned use cases `TypeId` needs to always be provided to allocations and deallocations of `Sized` Types and `N` `Sized` Types . Layout looks like the best place to ensure `TypeId` is always passed.

`Layout` would have `type_id_` added and `TypeId` implementation would be changed to `NonZeroU64`. `type_id_` would not be considered by `Eq`, so as not to break compatibility.
```rust
pub struct Layout {
    size_: usize,
    align_: NonZeroUsize,
    type_id_: Option<TypeId>
}
```

#### Drawbacks
Adding another field to Layout could have a tiny performance cost.

####  alternatives
Originally I had wanted a separate set of functions for this use case analogous to `Alloc::{alloc,dealloc}_array` and `Alloc::{alloc,dealloc}_one` (like below), but this allows for human error (E.g calling the normal unsized set of functions when you have a sized type).

```rust
alloc_typed(&mut self, layout: Layout, _: TypeId) -> Result<NonNull<u8>, AllocErr> {
  alloc(self, layout)
}
```

**Comment by Avi-D-coder** [comment]
@gnzlbg your right they are compatible, but this proposal is specifically about always passing type information from boxing one or `N` of  a `T`, not type-specific allocators. Once specialization lands `TypedAlloc: Alloc` would be interesting, but it's orthogonal to my use case.

[`ObjectAlloc`](https://docs.rs/object-alloc/0.2.0/object_alloc/trait.ObjectAlloc.html) is very similar to `TypedAlloc`.

**Comment by comex** [comment]
Note that [another recent RFC](https://github.com/rust-lang/rfcs/pull/2756) is proposing to allow transmutes between `Vec<A>` and `Vec<B>` as long as `A` and `B` have the same size and alignment.  This would allow a `Vec`'s contents to be deallocated with a different TypeId than the one it was allocated with.

**Comment by gnzlbg** [comment]
@comex That would forbid `Vec` from using the type aware allocator API, but I don't see a reasonable `Vec` implementation that would use such an API.

**Comment by gnzlbg** [comment]
> Adding another field to Layout could have a tiny performance cost.

Currently `Layout` is two `usize`s. Most ABIs allow passing and returning two `usizes`s in registers, which means that returning Layout from a function is as efficient as just returning an `usize`. 

This proposal adds another two fields to `Layout` (the enum discriminant and the `u64` TypeId`), changing how `Layout` is passed on most ABIs, from registers, to requiring that it must be passed via memory. 

I'm not sure of what the performance implications of that are, but would rather not do it I think.

**Comment by Avi-D-coder** [comment]
@gnzlbg The proposal includes changing `TypeId` from `u64` to `NonZeroU64`. `Option<std::num::NonZeroU64>` is packed into 8 bytes. So this changes requires 8 bytes more be passed as an argument.

> Most ABIs allow passing and returning two `usize`s in registers, which means that returning Layout from a function is as efficient as just returning an `usize`.

Do any calling convention besides `fastcall` make this restriction? I believe `fastcall` is the only one. More modern conventions seem to mostly allow 4+ integer registers.

I would also suspect LTO to remove the unused argument for allocators that don't use `TypeId`?

This is all likely moot, since https://github.com/rust-lang/rust/issues/26494 implies `Layout` and all small structs are passed on the stack anyway. In other words, in practice there will be no measurable performance cost. If your still not convinced I could implement the change and benchmark it?

**Comment by Avi-D-coder** [comment]
@comex If that RFC goes through, type-aware allocators will just have to account for deallocation not having an accurate `TypeId`. From my perspective it's not a deal breaker, just an interesting edge case.

**Comment by gnzlbg** [comment]
> I would also suspect LTO to remove the unused argument for allocators that don't use TypeId?

No, this isn't possible. The arguments are always passed according to the calling convention, and the global allocator functions cannot, in general, be inlined. You can, e.g., change the allocator at run-time, using `LD_PRELOAD`. 

> Do any calling convention besides fastcall make this restriction?

I thought actually that most ABIs make this restriction for return types (not arguments), and we have a couple of APIs that return Layouts IIRC.

**Comment by gnzlbg** [comment]
> This is all likely moot, since rust-lang/rust#26494 implies Layout and all small structs are passed on the stack anyway.

We pass scalars and scalar pairs in registers, and have two separate ABI classes for those in the Rust ABI (`Abi::Scalar` and `Abi::ScalarPair`)

**Comment by Avi-D-coder** [comment]
@gnzlbg That could be a problem.
Is there a reason the rust ABI could not have a`ScalarTriple`?
Does a calling convention agnostic optimization exist to pass the first two fields of a struct in registers and not the third?

I'll have to benchmark this. 
Is there a possible way to provide type information to a global allocator, that does not hit this restriction?
 If not, it's trade off between avoiding passing a struct on the stack or ever having type-aware global allocators and all the optimizations and concurrency advantages they can provide.

**Comment by gnzlbg** [comment]
I think you are focusing too much on how to implement something, and not on making a case for this feature. To me at least it is very unclear:

* What is precisely the problem that this API should solve? (you mention many cases, but do not explain any in detail)
* What are the constraints on solutions to that problem? (you mention that this feature enables many optimizations in those cases, but do not explain any of those optimizations in detail)
* What would the semantics of potential solutions be? (you only focus on syntax, e.g., how do we pass the `TypeId`)

I see many fundamental problems with the approach. First: 

* In the rust abstract machine memory is untyped, so one can allocate memory for an `Option<bool>`, and transmute that in place to a `bool`, and free the `bool`. A lot of correct code does this (which is why @comex probably mentioned the case of transmuting `Vec<A>` to `Vec<B>` above).

* `TypeId`s are not unique (e.g. see https://github.com/rust-lang/rust/issues/10389), so you can't rely on them for differentiating allocations of different types. (this also means that the actual layout of `TypeId` is unspecified and can change).

This means that the use cases that rely on accurate type information cannot really work, and that `TypeId` can at most be a hint. 

So if this is a hint, would such a hint be useful? 

No major allocator supports this (malloc, jemalloc, mimalloc, tcmalloc, weealloc, hurd, ...).

Some of the `std::collections` might be able to use it as a hint, e.g., `Vec<T>`/`Deque<T>`, but most other collections use the `Layout` builder methods to concatenate Layouts. It is unclear to me what would the result of concatenating two layouts with two different `Option<TypeId>`s be ? Probably `None` ? Some of the use-cases you mention, e.g., ECS, already use their own data-structures right ?

---

I can imagine that one can build an allocator that exploits `TypeId`, and that one could ship collections that are specifically written to use a `TypeId`-aware allocator for profit, and that one might want a different `TypedAlloc` trait for those, but making the standard collections exploit this would require changing their implementation, potentially significantly for the node based ones. And even then, most users using widely-used allocators won't benefit from it.

**Comment by Avi-D-coder** [comment]
I should have real code to publish, in the next couple of weeks. I'll publish a detailed write up with it including API requirements, trade-offs, benchmarks, etc...
For my use case transmuting is not an issue. Good to know about `TypeId` being a hash, it's not ideal but pretty simple to guard against in practice.

**Comment by glandium** [comment]
What's unclear to me is what that should be provided via `GlobalAlloc`. That's a very specific use case, and it could be fulfilled by opting in to using `Alloc`-aware types.

**Comment by Avi-D-coder** [comment]
I no longer believe passing `TypeId` is the correct solution. Specialization on generics is too useful a property. I'm going to need to do some more experimenting to find a better solution.
